zimzim_categoryproduct_category:
    path:     /
    defaults: { _controller: "ZIMZIMCategoryProductBundle:Category:index" }

zimzim_categoryproduct_category_show:
    path:     /{id}/show/
    defaults: { _controller: "ZIMZIMCategoryProductBundle:Category:show" }

zimzim_categoryproduct_category_new:
    path:     /new/
    defaults: { _controller: "ZIMZIMCategoryProductBundle:Category:new" }

zimzim_categoryproduct_category_create:
    path:     /create/
    defaults: { _controller: "ZIMZIMCategoryProductBundle:Category:create" }
    requirements: { _method: post }

zimzim_categoryproduct_category_edit:
    path:     /{id}/edit/
    defaults: { _controller: "ZIMZIMCategoryProductBundle:Category:edit" }

zimzim_categoryproduct_category_update:
    path:     /{id}/update/
    defaults: { _controller: "ZIMZIMCategoryProductBundle:Category:update" }
    requirements: { _method: post|put }

zimzim_categoryproduct_category_delete:
    path:     /{id}/delete/
    defaults: { _controller: "ZIMZIMCategoryProductBundle:Category:delete" }
    requirements: { _method: post|delete }
